name: Deploy via SSH
on:
  push:
    branches: [ "main" ] # adjust branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/u405460257/domains/nexusedu.org/public_html/cybermediks_new
            git reset --hard
            git pull origin main
            # Optional: run post-deploy tasks
            # /usr/bin/php artisan migrate --force
            # /usr/bin/php artisan config:cache
